version: "1.0"
info:
  model: int-scaffold
packages:
- name: Man01SabreenProject
  gitServerName: Adapters
  gitUrl: https://github.com/Sabreen0606
  gitUsername: Sephali-Smrutisikha-IBM-1
  gitBranch: main
